export { ensureExtensions } from './extension_ensure';
export { closeExtension } from './extension_close';
export { deleteExtension } from './extension_delete';
export { destroyExtension } from './extension_destroy';
export { listExtensions } from './extension_list';
export { loadExtension } from './extension_load';
export { readExtensionManifest } from './extension_read';
export { readExtensionManifestFromDirectory } from './extension_read';
export { importExtensions } from './extension_import';
export { openRoot } from './extension_open_root';
export { watchExtensions } from './extension_watch';
export { ExtensionRegistry } from './extension_registry';
export { ExtensionStorage } from './extension_store';
export type { Extension, ExtensionManifest, ExtensionMetadata } from './extension_types';
